version: '3'
services:
  producer1:    
    image: architect-team-project-producer-api:0.0.2
    hostname: producer1
    restart: "no"
    ports:
      - "8501:8501"
    extra_hosts: 
      - localhost:host-gateway
  producer2:    
    image: architect-team-project-producer-api:0.0.2
    hostname: producer2
    restart: "no"
    ports:
      - "8502:8501"
    extra_hosts: 
      - localhost:host-gateway
  producer3:    
    image: architect-team-project-producer-api:0.0.2
    hostname: producer3
    restart: "no"
    ports:
    - "8503:8501"
    extra_hosts: 
      - localhost:host-gateway
  producer4:    
    image: architect-team-project-producer-api:0.0.2
    hostname: producer4
    restart: "no"
    ports:
    - "8504:8501"
    extra_hosts: 
      - localhost:host-gateway
  producer5:    
    image: architect-team-project-producer-api:0.0.2
    hostname: producer5
    restart: "no"
    ports:
    - "8505:8501"
    extra_hosts: 
      - localhost:host-gateway
