server:
  port: 8082

spring:
  application:
    name: consumerService
  cloud:
    stream:
      bindings:
        "iot.event":
          destination: iot.event
          content-type: application/json
          # rabbit-event or kafka-event
          binder: rabbit-event
      # rabbit-event or kafka-event
      default-binder: rabbit-event
      binders:
        rabbit-event:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                username: guest
                password: guest
        kafka-event:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      zkNodes: localhost
                      brokers: localhost
