server:
  port: 8080

logging:
  config: classpath:log4j2.yml

spring:
  application:
    name: consumerService
  cloud:
    stream:
      bindings:
        input1:
          destination: iot.event
          content-type: application/json
          # rabbit-event or kafka-event
          binder: rabbit-event
          # group: iot
        # input2:
        #   destination: iot.event
        #   content-type: application/json
        #   # rabbit-event or kafka-event
        #   binder: rabbit-event
          # group: iot
      # rabbit-event or kafka-event
      default-binder: rabbit-event
      binders:
        rabbit-event:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                username: guest
                password: guest
        kafka-event:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      zkNodes: localhost
                      brokers: localhost
      # rabbit:
      #   bindings:
      #     "iot.event":
      #       consumer:
      #         max-concurrency: 5