apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: team2-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: custom-auto-scaler
          servicePort: 8080