apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-producer2
spec:
  selector:
    matchLabels:
      app: rabbitmq-producer2
  template:
    metadata:
      labels:
        app: rabbitmq-producer2
    spec:
      containers:
        - name: rabbitmq-producer2
          image: gcr.io/architect-certification-289902/23/rabbitmq-producer:latest
          ports:
          - containerPort: 8100
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: GOOGLE_CLOUD_PROJECT
              value: architect-certification-289902
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-producer2
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-producer2
  ports:
  - port: 8100