server:
  port: 8501

spring:
  application:
    name: producerService
  cloud:
    stream:
      bindings:
        "iot.event":
          destination: iot.event
          content-type: application/json
          binder: kafka-event 
      default-binder: kafka-event
      binders:
        kafka-event:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      zkNodes: localhost
                      brokers: localhost
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
